/* Service page content — the only file to edit when changing service-page text.
   After editing, run:  node scripts/build-services.js
   Keep content general and accurate: no company-specific claims (lanes, carriers, transit times, stats). */

const LABELS = {
  en: {
    quote: 'Get a quote',
    included: "What's included",
    steps: 'How it works',
    documents: "Documents you'll need",
    documentsNote: 'Exact requirements depend on the goods and the countries involved — we confirm the list with your quote.',
    faq: 'Questions',
    related: 'Related services',
    back: 'All services',
  },
  ar: {
    quote: 'اطلب عرض سعر',
    included: 'ما تشمله الخدمة',
    steps: 'كيف نعمل',
    documents: 'المستندات المطلوبة',
    documentsNote: 'تختلف المتطلبات بحسب البضاعة والدول المعنية — نؤكد لك القائمة مع عرض السعر.',
    faq: 'أسئلة شائعة',
    related: 'خدمات ذات صلة',
    back: 'كل الخدمات',
  },
};

const SERVICES = [
  {
    key: 'ocean',
    slug: 'ocean-freight',
    related: ['customs', 'land'],
    en: {
      title: 'Ocean Freight',
      kicker: 'FCL · LCL',
      lead: 'Container shipping between the world’s major ports — port to port, or door to door with pickup, clearance and delivery arranged for you.',
      metaDescription: 'Ocean freight to and from Kuwait: full container (FCL) and shared container (LCL) shipping, port to port or door to door, arranged by Nayef Bashar Trading Est.',
      included: [
        { title: 'Full container load (FCL)', body: '20ft, 40ft and 40ft high-cube containers reserved for your cargo alone.' },
        { title: 'Less than container load (LCL)', body: 'Share container space and pay only for the volume you use when your cargo won’t fill a container.' },
        { title: 'Special equipment', body: 'Refrigerated, open-top and flat-rack containers for temperature-controlled or oversized cargo.' },
        { title: 'Door to door', body: 'Pickup at origin, export and import clearance, and final delivery in one booking.' },
      ],
      steps: [
        { title: 'Share the details', body: 'Goods, weight and volume, origin, destination, and your Incoterm.' },
        { title: 'Quote and booking', body: 'We recommend FCL or LCL, confirm the schedule and book space with the carrier.' },
        { title: 'Loading and departure', body: 'Pickup, export clearance and loading at the port of origin.' },
        { title: 'Arrival and delivery', body: 'Import clearance at destination and delivery to your door.' },
      ],
      documents: ['Commercial invoice', 'Packing list', 'Bill of lading (issued by the carrier)', 'Certificate of origin', 'Permits or approvals for restricted goods'],
      faqs: [
        { q: 'Should I ship FCL or LCL?', a: 'If your cargo fills most of a container, FCL is usually better value and faster. For smaller shipments, LCL lets you share space and pay for your volume only. We compare both with your quote.' },
        { q: 'What are demurrage and detention?', a: 'Carriers allow a number of free days. Demurrage is charged when a container stays in the port beyond them; detention when it is kept outside the port too long. Having documents ready before arrival is the best way to avoid both.' },
        { q: 'Which Incoterms do you work with?', a: 'Tell us the Incoterm on your purchase or sale — for example EXW, FOB or CIF — and we quote the parts of the journey you are responsible for.' },
      ],
    },
    ar: {
      title: 'الشحن البحري',
      kicker: 'حاويات كاملة · جزئية',
      lead: 'شحن الحاويات بين أهم موانئ العالم — من ميناء إلى ميناء، أو من الباب إلى الباب مع ترتيب الاستلام والتخليص والتسليم.',
      metaDescription: 'شحن بحري من وإلى الكويت: حاويات كاملة وجزئية، من ميناء إلى ميناء أو من الباب إلى الباب، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'حاوية كاملة (FCL)', body: 'حاويات ٢٠ قدماً و٤٠ قدماً و٤٠ قدماً عالية مخصصة لبضاعتك وحدها.' },
        { title: 'شحن جزئي (LCL)', body: 'تشارك مساحة الحاوية وتدفع فقط مقابل الحجم الذي تستخدمه عندما لا تملأ بضاعتك حاوية كاملة.' },
        { title: 'معدات خاصة', body: 'حاويات مبردة ومفتوحة السقف ومسطحة للبضائع التي تحتاج تبريداً أو ذات الأحجام الكبيرة.' },
        { title: 'من الباب إلى الباب', body: 'الاستلام من المنشأ، وتخليص التصدير والاستيراد، والتسليم النهائي في حجز واحد.' },
      ],
      steps: [
        { title: 'شاركنا التفاصيل', body: 'البضاعة، والوزن والحجم، والمنشأ، والوجهة، وشرط التسليم (Incoterm).' },
        { title: 'العرض والحجز', body: 'نقترح الحاوية الكاملة أو الجزئية، ونؤكد الموعد ونحجز المساحة لدى الناقل.' },
        { title: 'التحميل والمغادرة', body: 'الاستلام وتخليص التصدير والتحميل في ميناء المنشأ.' },
        { title: 'الوصول والتسليم', body: 'تخليص الاستيراد في بلد الوصول والتسليم إلى بابك.' },
      ],
      documents: ['الفاتورة التجارية', 'قائمة التعبئة', 'بوليصة الشحن (يصدرها الناقل)', 'شهادة المنشأ', 'التصاريح أو الموافقات للبضائع المقيدة'],
      faqs: [
        { q: 'هل أشحن بحاوية كاملة أم جزئية؟', a: 'إذا كانت بضاعتك تملأ معظم الحاوية، فالحاوية الكاملة غالباً أوفر وأسرع. وللشحنات الصغيرة يتيح الشحن الجزئي مشاركة المساحة والدفع مقابل حجمك فقط. نقارن الخيارين في عرض السعر.' },
        { q: 'ما هي رسوم الديمريج والاحتجاز؟', a: 'يمنح الناقلون عدداً من الأيام المجانية. الديمريج رسم يُفرض عند بقاء الحاوية في الميناء بعدها، والاحتجاز عند إبقائها خارج الميناء مدة أطول. تجهيز المستندات قبل الوصول هو أفضل طريقة لتجنبهما.' },
        { q: 'ما شروط التسليم (Incoterms) التي تعملون بها؟', a: 'أخبرنا بشرط التسليم في عقد الشراء أو البيع — مثل EXW أو FOB أو CIF — وسنسعّر أجزاء الرحلة التي تقع على مسؤوليتك.' },
      ],
    },
  },
  {
    key: 'air',
    slug: 'air-freight',
    related: ['customs', 'ocean'],
    en: {
      title: 'Air Freight',
      kicker: 'Express · Consolidated',
      lead: 'Time-critical cargo on the fastest available routes — airport to airport, or door to door with clearance at both ends.',
      metaDescription: 'Air freight to and from Kuwait: express and consolidated air cargo, airport to airport or door to door, arranged by Nayef Bashar Trading Est.',
      included: [
        { title: 'Express', body: 'The earliest available flights for urgent shipments.' },
        { title: 'Consolidated', body: 'Your cargo travels with other shipments for a lower rate when timing is flexible.' },
        { title: 'Special cargo', body: 'Perishables, valuables and properly declared dangerous goods, subject to airline acceptance.' },
        { title: 'Door to door', body: 'Pickup, export and import clearance, and delivery to your address.' },
      ],
      steps: [
        { title: 'Share the details', body: 'Goods, number of pieces, weight and dimensions, and when it must arrive.' },
        { title: 'Quote and booking', body: 'We compare routes and flights and book the option that meets your deadline.' },
        { title: 'Departure', body: 'Pickup, export clearance and handover to the airline.' },
        { title: 'Arrival and delivery', body: 'Import clearance and delivery to your door.' },
      ],
      documents: ['Commercial invoice', 'Packing list', 'Air waybill (issued for the flight)', 'Certificate of origin', 'Safety data sheet for dangerous goods, including batteries'],
      faqs: [
        { q: 'How is the air freight price calculated?', a: 'Airlines charge on the chargeable weight: the greater of the actual weight and the volumetric weight. Volumetric weight is length × width × height in centimetres divided by 6,000. Compact, heavy cargo is the best value by air.' },
        { q: 'Can I ship lithium batteries or other dangerous goods?', a: 'Often yes, but they must be declared, packed and labelled under IATA dangerous goods rules, and some airlines refuse certain items. Tell us before booking so we can confirm acceptance.' },
        { q: 'How fast is air freight?', a: 'It depends on the route and flight availability. We give you the expected schedule with each quote.' },
      ],
    },
    ar: {
      title: 'الشحن الجوي',
      kicker: 'سريع · مجمّع',
      lead: 'شحنات عاجلة على أسرع المسارات المتاحة — من مطار إلى مطار، أو من الباب إلى الباب مع التخليص في الطرفين.',
      metaDescription: 'شحن جوي من وإلى الكويت: شحن سريع ومجمّع، من مطار إلى مطار أو من الباب إلى الباب، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'سريع', body: 'أقرب الرحلات المتاحة للشحنات العاجلة.' },
        { title: 'مجمّع', body: 'تُشحن بضاعتك مع شحنات أخرى بسعر أقل عندما يكون الموعد مرناً.' },
        { title: 'بضائع خاصة', body: 'المواد القابلة للتلف والثمينة والبضائع الخطرة المصرّح عنها بشكل صحيح، وفق قبول شركة الطيران.' },
        { title: 'من الباب إلى الباب', body: 'الاستلام، وتخليص التصدير والاستيراد، والتسليم إلى عنوانك.' },
      ],
      steps: [
        { title: 'شاركنا التفاصيل', body: 'البضاعة، وعدد الطرود، والوزن والأبعاد، وموعد الوصول المطلوب.' },
        { title: 'العرض والحجز', body: 'نقارن المسارات والرحلات ونحجز الخيار الذي يحقق موعدك.' },
        { title: 'المغادرة', body: 'الاستلام وتخليص التصدير والتسليم لشركة الطيران.' },
        { title: 'الوصول والتسليم', body: 'تخليص الاستيراد والتسليم إلى بابك.' },
      ],
      documents: ['الفاتورة التجارية', 'قائمة التعبئة', 'بوليصة الشحن الجوي (تصدر للرحلة)', 'شهادة المنشأ', 'نشرة بيانات السلامة للبضائع الخطرة، بما فيها البطاريات'],
      faqs: [
        { q: 'كيف يُحسب سعر الشحن الجوي؟', a: 'تحتسب شركات الطيران السعر على الوزن المحتسب: الأكبر بين الوزن الفعلي والوزن الحجمي. الوزن الحجمي هو الطول × العرض × الارتفاع بالسنتيمتر مقسوماً على ٦٠٠٠. البضائع الثقيلة صغيرة الحجم هي الأوفر جواً.' },
        { q: 'هل يمكنني شحن بطاريات الليثيوم أو بضائع خطرة أخرى؟', a: 'غالباً نعم، لكن يجب التصريح عنها وتعبئتها ووسمها وفق قواعد اتحاد النقل الجوي الدولي (IATA) للبضائع الخطرة، وبعض شركات الطيران ترفض مواد معينة. أخبرنا قبل الحجز لنؤكد القبول.' },
        { q: 'ما سرعة الشحن الجوي؟', a: 'تعتمد على المسار وتوفر الرحلات. نعطيك الجدول المتوقع مع كل عرض سعر.' },
      ],
    },
  },
  {
    key: 'land',
    slug: 'land-freight',
    related: ['customs', 'supply'],
    en: {
      title: 'Land Freight',
      kicker: 'FTL · LTL · Cross-border',
      lead: 'Road transport within Kuwait and across borders, from a single pallet to a full trailer.',
      metaDescription: 'Land freight from and to Kuwait: full truckload (FTL), part load (LTL) and cross-border road transport across the GCC and beyond, arranged by Nayef Bashar Trading Est.',
      included: [
        { title: 'Full truckload (FTL)', body: 'A dedicated truck for your cargo, direct from pickup to delivery.' },
        { title: 'Part load (LTL)', body: 'Share truck space for smaller shipments and pay for the space you use.' },
        { title: 'Cross-border', body: 'Road transport between Kuwait, the GCC and neighbouring countries, with border formalities handled.' },
        { title: 'Specialised trucks', body: 'Flatbeds, curtain-siders and refrigerated trucks to suit the cargo.' },
      ],
      steps: [
        { title: 'Share the details', body: 'Goods, weight, number of pallets, pickup and delivery addresses.' },
        { title: 'Quote and booking', body: 'We choose FTL or LTL and the right truck type, and confirm the pickup date.' },
        { title: 'Pickup and border crossing', body: 'Loading, export formalities and customs at each border.' },
        { title: 'Delivery', body: 'Import clearance at destination and delivery to the receiver.' },
      ],
      documents: ['Commercial invoice', 'Packing list', 'CMR consignment note', 'Certificate of origin', 'Transit documents where cargo crosses a third country'],
      faqs: [
        { q: 'Should I choose FTL or LTL?', a: 'FTL suits shipments that fill most of a truck or need to move directly and quickly. LTL is more economical for a few pallets.' },
        { q: 'Do goods made in the GCC pay customs duty?', a: 'Goods of GCC national origin generally move between member states free of customs duty when they have a valid GCC certificate of origin. Other goods are charged under the common customs tariff.' },
        { q: 'What slows down a border crossing?', a: 'Missing or inconsistent documents are the most common cause. We check your invoice, packing list and certificates before the truck leaves.' },
      ],
    },
    ar: {
      title: 'الشحن البري',
      kicker: 'حمولة كاملة · جزئية · عبر الحدود',
      lead: 'نقل بري داخل الكويت وعبر الحدود، من طبلية واحدة إلى مقطورة كاملة.',
      metaDescription: 'شحن بري من وإلى الكويت: حمولة كاملة وجزئية ونقل بري عبر الحدود في دول الخليج وما بعدها، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'حمولة كاملة (FTL)', body: 'شاحنة مخصصة لبضاعتك، مباشرة من الاستلام إلى التسليم.' },
        { title: 'حمولة جزئية (LTL)', body: 'تشارك مساحة الشاحنة للشحنات الصغيرة وتدفع مقابل المساحة التي تستخدمها.' },
        { title: 'عبر الحدود', body: 'نقل بري بين الكويت ودول الخليج والدول المجاورة مع إنجاز إجراءات الحدود.' },
        { title: 'شاحنات متخصصة', body: 'شاحنات مسطحة وستائرية ومبردة حسب نوع البضاعة.' },
      ],
      steps: [
        { title: 'شاركنا التفاصيل', body: 'البضاعة، والوزن، وعدد الطبليات، وعنواني الاستلام والتسليم.' },
        { title: 'العرض والحجز', body: 'نختار الحمولة الكاملة أو الجزئية ونوع الشاحنة المناسب، ونؤكد موعد الاستلام.' },
        { title: 'الاستلام وعبور الحدود', body: 'التحميل وإجراءات التصدير والجمارك عند كل حدود.' },
        { title: 'التسليم', body: 'تخليص الاستيراد في بلد الوصول والتسليم إلى المستلم.' },
      ],
      documents: ['الفاتورة التجارية', 'قائمة التعبئة', 'إرسالية CMR', 'شهادة المنشأ', 'مستندات العبور عند المرور بدولة ثالثة'],
      faqs: [
        { q: 'هل أختار حمولة كاملة أم جزئية؟', a: 'تناسب الحمولة الكاملة الشحنات التي تملأ معظم الشاحنة أو تحتاج نقلاً مباشراً وسريعاً. أما الجزئية فأوفر لعدد قليل من الطبليات.' },
        { q: 'هل تدفع البضائع الخليجية المنشأ رسوماً جمركية؟', a: 'تنتقل البضائع ذات المنشأ الوطني الخليجي بين الدول الأعضاء عموماً معفاة من الرسوم الجمركية عند وجود شهادة منشأ خليجية سارية. أما غيرها فتخضع للتعرفة الجمركية الموحدة.' },
        { q: 'ما الذي يؤخر عبور الحدود؟', a: 'أكثر الأسباب شيوعاً المستندات الناقصة أو غير المتطابقة. نراجع الفاتورة وقائمة التعبئة والشهادات قبل تحرك الشاحنة.' },
      ],
    },
  },
  {
    key: 'customs',
    slug: 'customs-clearance',
    related: ['ocean', 'air'],
    en: {
      title: 'Customs Clearance',
      kicker: 'Import · Export · Transit',
      lead: 'Declarations, duties and documentation handled so your cargo clears without delay — arranged directly or through a licensed customs broker.',
      metaDescription: 'Customs clearance in Kuwait for imports, exports and transit: declarations, HS classification, duties and permits, arranged by Nayef Bashar Trading Est.',
      included: [
        { title: 'Import clearance', body: 'Declaration, duty payment and release of your goods on arrival in Kuwait.' },
        { title: 'Export clearance', body: 'Export declarations and documents so cargo leaves on schedule.' },
        { title: 'Transit', body: 'Formalities for goods passing through Kuwait to another country.' },
        { title: 'Classification and permits', body: 'HS code classification, duty estimates, and coordination of approvals from the relevant authorities.' },
      ],
      steps: [
        { title: 'Send the documents', body: 'Invoice, packing list, transport document and certificate of origin.' },
        { title: 'Review and classify', body: 'We check the documents and confirm the HS code and expected duties.' },
        { title: 'Declare and pay', body: 'The declaration is submitted and duties and fees are paid.' },
        { title: 'Inspect and release', body: 'Any inspection is completed and the goods are released for delivery.' },
      ],
      documents: ['Commercial invoice', 'Packing list', 'Bill of lading, air waybill or CMR', 'Certificate of origin', 'Importer’s commercial or import licence', 'Approvals for restricted goods'],
      faqs: [
        { q: 'What is an HS code and why does it matter?', a: 'The Harmonized System code classifies your goods for customs. It decides the duty rate and whether a permit is needed, so the right code avoids overpaying and delays.' },
        { q: 'How long does clearance take?', a: 'It depends on the goods, the completeness of the documents and whether customs inspects the cargo. Complete, consistent documents are the fastest route.' },
        { q: 'What happens if documents are missing or wrong?', a: 'Customs can hold the goods until they are corrected, and storage or demurrage charges may build up. We review documents before arrival to prevent this.' },
      ],
    },
    ar: {
      title: 'التخليص الجمركي',
      kicker: 'استيراد · تصدير · ترانزيت',
      lead: 'البيانات الجمركية والرسوم والمستندات تُنجز لتُخلَّص بضاعتك دون تأخير — مباشرةً أو من خلال مخلص جمركي مرخص.',
      metaDescription: 'تخليص جمركي في الكويت للاستيراد والتصدير والترانزيت: البيانات الجمركية وتصنيف البنود والرسوم والتصاريح، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'تخليص الاستيراد', body: 'البيان الجمركي ودفع الرسوم والإفراج عن بضاعتك عند وصولها إلى الكويت.' },
        { title: 'تخليص التصدير', body: 'بيانات ومستندات التصدير لتغادر البضاعة في موعدها.' },
        { title: 'الترانزيت', body: 'إجراءات البضائع العابرة عبر الكويت إلى دولة أخرى.' },
        { title: 'التصنيف والتصاريح', body: 'تصنيف البند الجمركي (HS)، وتقدير الرسوم، وتنسيق الموافقات مع الجهات المختصة.' },
      ],
      steps: [
        { title: 'أرسل المستندات', body: 'الفاتورة، وقائمة التعبئة، ومستند النقل، وشهادة المنشأ.' },
        { title: 'المراجعة والتصنيف', body: 'نراجع المستندات ونؤكد البند الجمركي والرسوم المتوقعة.' },
        { title: 'التصريح والدفع', body: 'يُقدَّم البيان الجمركي وتُدفع الرسوم.' },
        { title: 'الفحص والإفراج', body: 'يُستكمل أي فحص ويُفرج عن البضاعة للتسليم.' },
      ],
      documents: ['الفاتورة التجارية', 'قائمة التعبئة', 'بوليصة الشحن البحري أو الجوي أو إرسالية CMR', 'شهادة المنشأ', 'الرخصة التجارية أو رخصة الاستيراد للمستورد', 'الموافقات للبضائع المقيدة'],
      faqs: [
        { q: 'ما هو البند الجمركي (HS) ولماذا يهم؟', a: 'رمز النظام المنسق يصنّف بضاعتك لدى الجمارك، ويحدد نسبة الرسوم وما إذا كان التصريح مطلوباً، لذا فالرمز الصحيح يجنبك دفع زيادة والتأخير.' },
        { q: 'كم يستغرق التخليص؟', a: 'يعتمد على نوع البضاعة واكتمال المستندات وما إذا فحصت الجمارك الشحنة. المستندات الكاملة والمتطابقة هي الطريق الأسرع.' },
        { q: 'ماذا يحدث إذا كانت المستندات ناقصة أو خاطئة؟', a: 'قد تحتجز الجمارك البضاعة حتى تُصحَّح، وقد تتراكم رسوم التخزين أو الديمريج. نراجع المستندات قبل الوصول لتفادي ذلك.' },
      ],
    },
  },
  {
    key: 'trade',
    slug: 'import-export',
    related: ['customs', 'supply'],
    en: {
      title: 'Import & Export',
      kicker: 'Sourcing · Commission agent',
      lead: 'Trade support for companies buying from and selling to international markets — we act as your commission agent between you, your suppliers and the carriers.',
      metaDescription: 'Import and export support from Kuwait: commission agent services, supplier coordination, trade documents and Incoterms guidance, by Nayef Bashar Trading Est.',
      included: [
        { title: 'Commission agent', body: 'We act on your behalf with suppliers and buyers and are paid a commission for arranging the trade.' },
        { title: 'Supplier coordination', body: 'Follow-up on orders, production readiness and pickup dates with your suppliers.' },
        { title: 'Trade documents', body: 'Invoices, packing lists and certificates prepared to match your payment terms, including letters of credit.' },
        { title: 'Shipping and clearance', body: 'The goods move by sea, air or land and clear customs at both ends.' },
      ],
      steps: [
        { title: 'Tell us what you trade', body: 'The goods, the supplier or buyer, quantities and target dates.' },
        { title: 'Agree terms', body: 'We confirm Incoterms, documents and the commission for our work.' },
        { title: 'Coordinate the order', body: 'We follow up with the supplier and arrange pickup and shipping.' },
        { title: 'Deliver and close', body: 'Customs clearance, delivery and a complete set of documents for your records.' },
      ],
      documents: ['Purchase order or sales contract', 'Proforma and commercial invoice', 'Packing list', 'Certificate of origin', 'Letter of credit terms, if used'],
      faqs: [
        { q: 'What does a commission agent do?', a: 'A commission agent acts for you in a trade — dealing with suppliers or buyers, coordinating orders and shipping — and is paid a commission rather than buying and reselling the goods.' },
        { q: 'Which Incoterm should I use?', a: 'It depends on how much of the journey and risk you want to control. EXW puts almost everything on the buyer; CIF and DAP put more on the seller. We explain the options for your deal.' },
        { q: 'Can you help if I pay by letter of credit?', a: 'Yes. Letters of credit require documents that match the credit exactly, so we align the shipping documents with its terms.' },
      ],
    },
    ar: {
      title: 'الاستيراد والتصدير',
      kicker: 'توريد · وكيل بالعمولة',
      lead: 'دعم تجاري للشركات التي تشتري من الأسواق الدولية وتبيع إليها — نعمل وكيلاً بالعمولة بينك وبين مورديك والناقلين.',
      metaDescription: 'دعم الاستيراد والتصدير من الكويت: خدمات الوكيل بالعمولة، وتنسيق الموردين، والمستندات التجارية، وشروط التسليم، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'وكيل بالعمولة', body: 'نعمل نيابةً عنك مع الموردين والمشترين ونتقاضى عمولة مقابل ترتيب الصفقة.' },
        { title: 'تنسيق الموردين', body: 'متابعة الطلبات وجاهزية الإنتاج ومواعيد الاستلام مع مورديك.' },
        { title: 'المستندات التجارية', body: 'فواتير وقوائم تعبئة وشهادات تُعدّ بما يتوافق مع شروط الدفع، بما فيها الاعتمادات المستندية.' },
        { title: 'الشحن والتخليص', body: 'تُنقل البضاعة بحراً أو جواً أو براً وتُخلَّص جمركياً في الطرفين.' },
      ],
      steps: [
        { title: 'أخبرنا بما تتاجر به', body: 'البضاعة، والمورد أو المشتري، والكميات، والمواعيد المستهدفة.' },
        { title: 'نتفق على الشروط', body: 'نؤكد شروط التسليم والمستندات والعمولة مقابل عملنا.' },
        { title: 'ننسق الطلب', body: 'نتابع مع المورد ونرتب الاستلام والشحن.' },
        { title: 'التسليم والإغلاق', body: 'التخليص الجمركي والتسليم ومجموعة كاملة من المستندات لسجلاتك.' },
      ],
      documents: ['أمر الشراء أو عقد البيع', 'الفاتورة المبدئية والتجارية', 'قائمة التعبئة', 'شهادة المنشأ', 'شروط الاعتماد المستندي عند استخدامه'],
      faqs: [
        { q: 'ما عمل الوكيل بالعمولة؟', a: 'يعمل الوكيل بالعمولة نيابةً عنك في الصفقة — يتعامل مع الموردين أو المشترين وينسق الطلبات والشحن — ويتقاضى عمولة بدلاً من شراء البضاعة وإعادة بيعها.' },
        { q: 'أي شرط تسليم أستخدم؟', a: 'يعتمد على مقدار الرحلة والمخاطر التي تريد التحكم بها. شرط EXW يضع كل شيء تقريباً على المشتري، بينما CIF وDAP يضعان المزيد على البائع. نشرح لك الخيارات المناسبة لصفقتك.' },
        { q: 'هل تساعدون إذا كان الدفع باعتماد مستندي؟', a: 'نعم. يتطلب الاعتماد المستندي مستندات مطابقة تماماً لشروطه، لذا نُعدّ مستندات الشحن بما يتوافق معها.' },
      ],
    },
  },
  {
    key: 'supply',
    slug: 'supply-chain',
    related: ['trade', 'ocean'],
    en: {
      title: 'Supply Chain Management',
      kicker: 'Planning · Coordination · Visibility',
      lead: 'End-to-end planning that connects every mode, every document and every hand-off into one flow, with one team accountable for all of it.',
      metaDescription: 'Supply chain management from Kuwait: route and mode planning, supplier consolidation, scheduling and milestone updates, by Nayef Bashar Trading Est.',
      included: [
        { title: 'Route and mode planning', body: 'The right mix of sea, air and road for your cost and deadline.' },
        { title: 'Consolidation', body: 'Goods from several suppliers combined into fewer, fuller shipments.' },
        { title: 'Scheduling', body: 'Pickups, departures and deliveries planned around your production or sales dates.' },
        { title: 'Milestone updates', body: 'One point of contact and an update at every step of every shipment.' },
      ],
      steps: [
        { title: 'Map your flows', body: 'Your suppliers, customers, volumes and deadlines.' },
        { title: 'Design the plan', body: 'Routes, modes and consolidation points that balance cost and time.' },
        { title: 'Run the shipments', body: 'Bookings, documents and clearance for each movement.' },
        { title: 'Review and improve', body: 'We review what worked and adjust the plan with you.' },
      ],
      documents: ['Supplier and customer list', 'Expected volumes and order schedule', 'Commercial invoices and packing lists per shipment', 'Certificates and permits for regulated goods'],
      faqs: [
        { q: 'When does supply chain management make sense?', a: 'When you ship regularly, buy from several suppliers, or combine sea, air and road. Planning the whole flow usually lowers cost and avoids missed deadlines.' },
        { q: 'Can shipments from different suppliers be combined?', a: 'Yes. Consolidating goods from several suppliers into one shipment reduces the number of bookings, documents and clearances.' },
        { q: 'How will I know the status of my shipments?', a: 'You have one point of contact and receive an update by WhatsApp or email at each milestone.' },
      ],
    },
    ar: {
      title: 'إدارة سلاسل الإمداد',
      kicker: 'تخطيط · تنسيق · متابعة',
      lead: 'تخطيط متكامل يربط كل وسيلة نقل وكل مستند وكل مرحلة تسليم في مسار واحد، مع فريق واحد مسؤول عن كل ذلك.',
      metaDescription: 'إدارة سلاسل الإمداد من الكويت: تخطيط المسارات ووسائل النقل، وتجميع الموردين، والجدولة، والتحديثات في كل مرحلة، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'تخطيط المسار ووسيلة النقل', body: 'المزيج المناسب من البحري والجوي والبري حسب التكلفة والموعد.' },
        { title: 'التجميع', body: 'تجميع بضائع عدة موردين في شحنات أقل وأكمل.' },
        { title: 'الجدولة', body: 'تخطيط الاستلام والمغادرة والتسليم وفق مواعيد إنتاجك أو مبيعاتك.' },
        { title: 'تحديثات في كل مرحلة', body: 'جهة تواصل واحدة وتحديث في كل خطوة من كل شحنة.' },
      ],
      steps: [
        { title: 'نرسم مسارات بضائعك', body: 'مورديك وعملاؤك والكميات والمواعيد.' },
        { title: 'نصمم الخطة', body: 'مسارات ووسائل نقل ونقاط تجميع توازن بين التكلفة والوقت.' },
        { title: 'ننفذ الشحنات', body: 'الحجوزات والمستندات والتخليص لكل عملية نقل.' },
        { title: 'نراجع ونحسّن', body: 'نراجع ما نجح ونعدّل الخطة معك.' },
      ],
      documents: ['قائمة الموردين والعملاء', 'الكميات المتوقعة وجدول الطلبات', 'الفواتير التجارية وقوائم التعبئة لكل شحنة', 'الشهادات والتصاريح للبضائع الخاضعة للرقابة'],
      faqs: [
        { q: 'متى تكون إدارة سلاسل الإمداد مفيدة؟', a: 'عندما تشحن بانتظام، أو تشتري من عدة موردين، أو تجمع بين الشحن البحري والجوي والبري. تخطيط المسار كاملاً يخفض التكلفة غالباً ويمنع تفويت المواعيد.' },
        { q: 'هل يمكن تجميع شحنات من موردين مختلفين؟', a: 'نعم. تجميع بضائع عدة موردين في شحنة واحدة يقلل عدد الحجوزات والمستندات وعمليات التخليص.' },
        { q: 'كيف أعرف حالة شحناتي؟', a: 'لديك جهة تواصل واحدة وتتلقى تحديثاً عبر واتساب أو البريد الإلكتروني في كل مرحلة.' },
      ],
    },
  },
  {
    key: 'freehand',
    slug: 'freehand-shipments',
    related: ['ocean', 'customs'],
    en: {
      title: 'Freehand Shipments',
      kicker: 'Shipper-controlled · CFR · CIF',
      lead: 'We choose the carrier, the routing and the schedule, and arrange the main international freight — one partner in control from booking to arrival.',
      metaDescription: 'Freehand shipments from Kuwait: the shipper’s forwarder selects the carrier, routing and schedule and arranges the main freight under terms like CFR or CIF, with Nayef Bashar Trading Est.',
      included: [
        { title: 'Carrier selection', body: 'We choose the shipping line or airline that fits your cargo, budget and deadline.' },
        { title: 'Routing and schedule', body: 'We plan the transit route and sailing or flight dates around your delivery date.' },
        { title: 'Main freight arranged and paid', body: 'The international freight is booked and paid at origin, as CFR and CIF terms require.' },
        { title: 'Cargo insurance under CIF', body: 'When you sell CIF, we arrange the insurance cover the term requires.' },
      ],
      steps: [
        { title: 'Share the details', body: 'Goods, weight and volume, origin, destination, and the Incoterm of your sale.' },
        { title: 'We choose carrier and route', body: 'We compare options and recommend the carrier, routing and schedule.' },
        { title: 'Booking and departure', body: 'We book space, prepare the documents and load at origin.' },
        { title: 'Arrival hand-over', body: 'We follow the cargo to destination and hand over to the buyer or their agent.' },
      ],
      documents: ['Commercial invoice', 'Packing list', 'Sales contract or proforma showing the Incoterm', 'Insurance certificate (for CIF)', 'Permits or approvals for restricted goods'],
      faqs: [
        { q: 'What is the difference between freehand and nominated cargo?', a: 'In a freehand shipment, the shipper or their forwarder chooses the carrier, routing and schedule. In a nominated shipment, the buyer chooses their own carrier or forwarder, and the shipper must follow the buyer’s booking instructions.' },
        { q: 'Which Incoterms usually go with freehand shipments?', a: 'Terms where the seller arranges and pays for the main transport, such as CFR and CIF (or CPT and CIP for other modes). Under CIF and CIP the seller also arranges insurance.' },
        { q: 'Will the buyer still see the shipment details?', a: 'Yes. We share the carrier, booking and bill of lading details so the buyer can plan clearance and collection at destination.' },
      ],
    },
    ar: {
      title: 'شحنات فري هاند',
      kicker: 'بتحكم الشاحن · CFR · CIF',
      lead: 'نختار الناقل والمسار والموعد، ونرتب الشحن الدولي الرئيسي — شريك واحد يتحكم بالشحنة من الحجز حتى الوصول.',
      metaDescription: 'شحنات فري هاند من الكويت: يختار وكيل الشحن التابع للشاحن الناقل والمسار والموعد ويرتب الشحن الرئيسي وفق شروط مثل CFR أو CIF، مع مؤسسة نايف بشر تجارية.',
      included: [
        { title: 'اختيار الناقل', body: 'نختار خط الشحن أو شركة الطيران المناسبة لبضاعتك وميزانيتك وموعدك.' },
        { title: 'المسار والجدول', body: 'نخطط مسار العبور ومواعيد الإبحار أو الطيران وفق موعد التسليم.' },
        { title: 'ترتيب الشحن الرئيسي ودفعه', body: 'يُحجز الشحن الدولي ويُدفع في بلد المنشأ، كما تتطلب شروط CFR وCIF.' },
        { title: 'تأمين البضاعة وفق CIF', body: 'عند البيع بشرط CIF نرتب التغطية التأمينية التي يتطلبها الشرط.' },
      ],
      steps: [
        { title: 'شاركنا التفاصيل', body: 'البضاعة، والوزن والحجم، والمنشأ، والوجهة، وشرط التسليم في عقد البيع.' },
        { title: 'نختار الناقل والمسار', body: 'نقارن الخيارات ونقترح الناقل والمسار والموعد.' },
        { title: 'الحجز والمغادرة', body: 'نحجز المساحة ونجهز المستندات ونحمّل البضاعة في المنشأ.' },
        { title: 'التسليم عند الوصول', body: 'نتابع البضاعة حتى الوجهة ونسلّمها للمشتري أو وكيله.' },
      ],
      documents: ['الفاتورة التجارية', 'قائمة التعبئة', 'عقد البيع أو الفاتورة المبدئية موضحاً فيها شرط التسليم', 'شهادة التأمين (لشرط CIF)', 'التصاريح أو الموافقات للبضائع المقيدة'],
      faqs: [
        { q: 'ما الفرق بين شحنات فري هاند والشحنات المُسمّاة (Nominated)؟', a: 'في شحنة فري هاند يختار الشاحن أو وكيل الشحن التابع له الناقل والمسار والموعد. أما في الشحنة المُسمّاة فيختار المشتري الناقل أو وكيل الشحن الخاص به، ويلتزم الشاحن بتعليمات الحجز التي يحددها المشتري.' },
        { q: 'ما شروط التسليم التي ترتبط عادةً بشحنات فري هاند؟', a: 'الشروط التي يرتب فيها البائع النقل الرئيسي ويدفع تكلفته، مثل CFR وCIF (أو CPT وCIP لوسائل النقل الأخرى). وفي شرطي CIF وCIP يرتب البائع التأمين أيضاً.' },
        { q: 'هل يطّلع المشتري على تفاصيل الشحنة؟', a: 'نعم. نشارك بيانات الناقل والحجز وبوليصة الشحن ليتمكن المشتري من التخطيط للتخليص والاستلام في بلد الوصول.' },
      ],
    },
  },
];

module.exports = { LABELS, SERVICES };
